name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pyhton
        uses: actions/setup_python@v4

        with: 
          python-version: '3.9'

      - name: Install dependencies
        run: 
          python -m pip instal --upgrade pip
          pip install pytest

      - name: Run Tests
        run: pytest
       